name: CI
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Install Go
              uses: actions/setup-go@v1
              with:
                  go-version: 1.17
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run tests
              run: go test ./...
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - uses: dominikh/staticcheck-action@v1.1.0
              with:
                  version: "2021.1.1"
